apiVersion: v1
kind: Namespace
metadata: { name: attack }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caldera
  namespace: attack
spec:
  replicas: 1
  selector: { matchLabels: { app: caldera } }
  template:
    metadata:
      labels: { app: caldera }
    spec:
      containers:
        - name: caldera
          image: mitre/caldera:4.2.0
          ports:
            - containerPort: 8888
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: caldera
  namespace: attack
spec:
  type: NodePort
  selector: { app: caldera }
  ports:
    - name: web
      port: 8888
      targetPort: 8888
      nodePort: 32000
