apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-nginx
  namespace: default
spec:
  mode: one
  selector:
    labelSelectors:
      app: demo-nginx
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "60s"
