apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-nginx
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      app: demo-nginx
  delay:
    latency: "200ms"
  duration: "45s"
