apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-nginx-pod
  namespace: default
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: demo-nginx
  duration: "30s"
